core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('account/', include('account.urls')),
    path('', include('pages.urls')),
    path("student_dashboard/",include('student.urls')),
    path("instructor_dashboard/",include('instaructor.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaructor/urls.py
from django.urls import path
from . import views
app_name = 'instructor'
urlpatterns = [
        path('', views.InstructorDashboardView.as_view(), name='instructor-dashboard'),
        path('courses/', views.InstructorCoursesView.as_view(), name='instructor_courses'),
        path('courses/<int:pk>/', views.InstructorCourseDetailView.as_view(), name='instructor_course_detail'),
        path('courses/<int:pk>/update/', views.InstructorCourseUpdateView.as_view(), name='instructor_course_update'),

]

course/models.py
from django.db import models
from django.contrib.auth.models import User
from django_ckeditor_5.fields import CKEditor5Field
from django.utils.text import slugify


# Define a reusable function to generate video upload path
def upload_to_course_video(instance, filename):
    instructor_username = instance.instructor.username
    course_title = instance.module.course.title  # Access the course title from the module
    return f'course_videos/{instructor_username}/{course_title}/{filename}'

# Choices for languages and difficulty levels
LANGUAGE_CHOICES = [
    ('en', 'English'),
    ('es', 'Spanish'),
    ('fr', 'French'),
    ('de', 'German'),
    ('it', 'Italian'),
]

DIFFICULTY_LEVEL_CHOICES = [
    ('beginner', 'Beginner'),
    ('intermediate', 'Intermediate'),
    ('advanced', 'Advanced'),
]

class Course(models.Model):
    title = models.CharField(max_length=255, help_text="Enter the title of the course")
    excerpt = models.TextField(help_text="Enter a short course description")
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    language = models.CharField(max_length=50, choices=LANGUAGE_CHOICES, help_text="Select the course language")
    is_certified = models.BooleanField(default=False, help_text="Check if the course is certified")
    is_free = models.BooleanField(default=False, help_text="Check if the course is free")
    image_thumbnail = models.ImageField(upload_to='course_thumbnails/', help_text="Upload an image thumbnail for the course")
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True, help_text="Enter the price of the course")
    what_youll_learn = models.TextField(help_text="Enter what students will learn")
    requirements = models.TextField(help_text="Enter course requirements")
    detailed_description = models.TextField(help_text="Enter a detailed course description")
    difficulty_level = models.CharField(max_length=20, choices=DIFFICULTY_LEVEL_CHOICES)
    is_public = models.BooleanField(default=False, help_text="Check if the course is public")
    video_intro = models.FileField(upload_to=upload_to_course_video, null=True, blank=True, help_text="Upload a video intro (e.g., MP4, AVI, MOV)")

    def __str__(self):
        return self.title

class Module(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
    module_name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.module_name

class Lesson(models.Model):
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='lessons_taught')
    module = models.ForeignKey(Module, on_delete=models.CASCADE, related_name='lessons')
    lesson_name = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    video = models.FileField(upload_to=upload_to_course_video, null=True, blank=True)
    attachment = models.FileField(upload_to='course_attachments/', null=True, blank=True)

    def __str__(self):
        return self.lesson_name

instaructor/models.py
from django.db import models

# Create your models here.

course/views.py
from django.shortcuts import render

# Create your views here.

instaructor/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from course.models import Course
class InstructorDashboardView(LoginRequiredMixin, TemplateView):
    template_name = "instructor_dashboard/instructor_dashboard.html"



class InstructorCoursesView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'instructor_dashboard/courses/instructor_courses.html'  
    context_object_name = 'courses'

    def get_queryset(self):
        user = self.request.user  # Get the currently logged-in user
        return Course.objects.filter(instructor=user)

class InstructorCourseDetailView(DetailView):
    model = Course
    template_name = 'instructor_dashboard/courses/course_detail.html' 
    context_object_name = 'course'

class InstructorCourseUpdateView(UpdateView):
    model = Course
    template_name = 'instructor_dashboard/courses/course_form.html'
    fields = '__all__'  # Use all fields from the Course model

instaructor/templates/instructor_dashboard/courses/course_detail.html
{% extends 'instructor/base_instructor.html' %}
{% block content %}
  <!-- Page header -->
  <div class="page-header d-print-none">
    <div class="container-xl">
      <div class="row g-2 align-items-center">
        <div class="col">
          <!-- Page pre-title -->
          <div class="page-pretitle">Overview</div>
          <h2 class="page-title">{{ course.title }}</h2>
        </div>
        <!-- Page title actions -->
        <div class="col-auto ms-auto d-print-none">
          <div class="btn-list">
            <span class="d-none d-sm-inline"><a href="#" class="btn">Update Course</a></span>
            <a href="#" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
              <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M12 5l0 14" />
                <path d="M5 12l14 0" />
              </svg>Delete Course
            </a>
            <a href="#" class="btn btn-primary d-sm-none btn-icon" data-bs-toggle="modal" data-bs-target="#modal-report" aria-label="Create new report">
              <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
              <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path stroke="none" d="M0 0h24v24H0z" fill="none" />
                <path d="M12 5l0 14" />
                <path d="M5 12l14 0" />
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <!-- Page body -->
  <div class="page-body">
    <div class="container-xl">
      <div class="row row-deck row-cards">
        <div class="col-12">
          <div class="card">
            <div class="card-body">
              <!-- Course Details -->
              <h1>{{ course.title }}</h1>
              <p>Instructor: {{ course.instructor }}</p>
              <p>Language: {{ course.get_language_display }}</p>
              <p>Difficulty Level: {{ course.get_difficulty_level_display }}</p>
              <!-- Add other course details as needed -->
            </div>
          </div>
        </div>
        <div class="col-8">
          <div class="card">
            {% for module in course.modules.all %}
              <div class="px-2">
                <h3 class="p-2 bg-purple-lt">{{ module.module_name }}</h3>
                <p class="px-2">{{ module.description|safe }}</p>
              </div>
              <div class="p-2">
                {% for lesson in module.lessons.all %}
                  <div>
                    <!-- Lesson icon from tabler.io -->

                    <h4 class="my-2  text-purple bg-transparent">
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-arrow-big-right-lines" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M12 9v-3.586a1 1 0 0 1 1.707 -.707l6.586 6.586a1 1 0 0 1 0 1.414l-6.586 6.586a1 1 0 0 1 -1.707 -.707v-3.586h-3v-6h3z"></path>
                        <path d="M3 9v6"></path>
                        <path d="M6 9v6"></path>
                      </svg>
                      {{ lesson.lesson_name }}
                    </h4>
                    <p>{{ lesson.content }}</p>
                    {% if lesson.attachment %}
                     atached file : <a href="{{ lesson.attachment.url }}" target="_blank">{{ lesson.attachment }}</a>
                    {% endif %}
                    
                    <!-- Display video if it exists -->
                    {% if lesson.video %}
                      <video controls class="card w-100 my-2">
                        <source src="{{ lesson.video.url }}" type="video/mp4" />Your browser does not support the video tag.
                      </video>
                    {% endif %}
                  </div>
                {% endfor %}
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="col-4">
          <div class="card p-2">
            <img src="{{ course.image_thumbnail.url }}" class="mb-2 rounded-3 border" />
            <p>what_youll_learn: {{ course.what_youll_learn|safe }}</p>
            <p>requirements: {{ course.requirements|safe }}</p>
            <p>detailed_description: {{ course.detailed_description|safe }}</p>
          </div>
        </div>
      </div>
    </div>
  </div>



{% endblock %}

instaructor/templates/instructor_dashboard/courses/instructor_courses.html
{% extends "instructor/base_instructor.html" %}
{% block content %}


        <!-- Page header -->
        <div class="page-header d-print-none">
            <div class="container-xl">
              <div class="row g-2 align-items-center">
                <div class="col">
                  <!-- Page pre-title -->
                  <div class="page-pretitle">
                    Overview
                  </div>
                  <h2 class="page-title">
                    My Courses                  
                </h2>
                </div>
                <!-- Page title actions -->
                <div class="col-auto ms-auto d-print-none">
                  <div class="btn-list">
                    <span class="d-none d-sm-inline">
                      <a href="#" class="btn">
                        Add New Course
                      </a>
                    </span>
                    <a href="#" class="btn btn-primary d-none d-sm-inline-block" data-bs-toggle="modal" data-bs-target="#modal-report">
                      <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                      Create new report
                    </a>
                    <a href="#" class="btn btn-primary d-sm-none btn-icon" data-bs-toggle="modal" data-bs-target="#modal-report" aria-label="Create new report">
                      <!-- Download SVG icon from http://tabler-icons.io/i/plus -->
                      <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 5l0 14" /><path d="M5 12l14 0" /></svg>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- Page body -->
          <div class="page-body">
            <div class="container-xl">
              <div class="row row-deck row-cards">
                {% for course in courses %}
                <div class="col-lg-12">
                    <div class="card">
                      <div class="row row-0">
                        <div class="col-3 p-1">
                          <!-- Photo -->
                          <img src="{{ course.image_thumbnail.url }}"
                           class="w-100 h-100 object-cover card-img-start" 
                           alt="{{ course.title }}">
                        </div>
                        <div class="col p-1">
                          <div class="card-body">
                            <h3 class="card-title"><a href="{% url 'instructor:instructor_course_detail' course.pk %}">{{ course.title }}</a></h3>
                            <p class="text-muted">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam deleniti fugit
                              incidunt, iste, itaque minima
                              neque pariatur perferendis sed suscipit velit vitae voluptatem.</p>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                    {% endfor %}
            
                
              </div>
            </div>
          </div>


{% endblock %}