core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('account/', include('account.urls')),
    path('', include('pages.urls')),
    path("student_dashboard/",include('student.urls')),
    path("instructor_dashboard/",include('instaructor.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instaructor/urls.py
from django.urls import path
from . import views
app_name = 'instructor'
urlpatterns = [
        path('', views.InstructorDashboardView.as_view(), name='instructor-dashboard'),
        path('courses/', views.InstructorCoursesView.as_view(), name='instructor_courses'),
        path('courses/<int:pk>/', views.InstructorCourseDetailView.as_view(), name='instructor_course_detail'),
        path('courses/<int:pk>/update/', views.InstructorCourseUpdateView.as_view(), name='instructor_course_update'),

]

instaructor/models.py
from django.db import models

# Create your models here.

instaructor/views.py
from django.shortcuts import render

from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from course.models import Course
class InstructorDashboardView(LoginRequiredMixin, TemplateView):
    template_name = "instructor_dashboard/instructor_dashboard.html"



class InstructorCoursesView(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'instructor_dashboard/courses/instructor_courses.html'  
    context_object_name = 'courses'

    def get_queryset(self):
        user = self.request.user  # Get the currently logged-in user
        return Course.objects.filter(instructor=user)

class InstructorCourseDetailView(DetailView):
    model = Course
    template_name = 'instructor_dashboard/courses/course_detail.html' 
    context_object_name = 'course'

class InstructorCourseUpdateView(UpdateView):
    model = Course
    template_name = 'instructor_dashboard/courses/course_form.html'
    fields = '__all__'  # Use all fields from the Course model

instaructor/templates/componenets/navbar.html
<div class="collapse navbar-collapse" id="sidebar-menu">
  <ul class="navbar-nav pt-lg-3">

    <li class="nav-item">
      <a class="nav-link" href="{% url 'instructor:instructor-dashboard'  %}">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
          <!-- Download SVG icon from http://tabler-icons.io/i/home -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M5 12l-2 0l9 -9l9 9l-2 0" />
            <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
            <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
          </svg>
        </span>
        <span class="nav-link-title">Dashboard</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="{% url 'instructor:instructor_courses'  %}">
        <span class="nav-link-icon d-md-none d-lg-inline-block">
          <!-- Download SVG icon from http://tabler-icons.io/i/home -->
          <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
            <path stroke="none" d="M0 0h24v24H0z" fill="none" />
            <path d="M5 12l-2 0l9 -9l9 9l-2 0" />
            <path d="M5 12v7a2 2 0 0 0 2 2h10a2 2 0 0 0 2 -2v-7" />
            <path d="M9 21v-6a2 2 0 0 1 2 -2h2a2 2 0 0 1 2 2v6" />
          </svg>
        </span>
        <span class="nav-link-title">My Courses</span>
      </a>
    </li>

  </ul>
</div>