account/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView, PasswordChangeView, 
    PasswordChangeDoneView, PasswordResetView,
    PasswordResetDoneView, PasswordResetConfirmView, 
    PasswordResetCompleteView)
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from .forms import AuthenticationForm, PasswordResetForm, SetPasswordForm, PasswordChangeForm
app_name = 'account_user'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='account/login.html'), name='login_account'),
    path('logout/', LogoutView.as_view(template_name='account/logout.html'), name='logout_account'),

    path('password-change/', PasswordChangeView.as_view(template_name='account/password_change_form.html',
                                                        form_class=PasswordChangeForm), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(
                                                    template_name='account/password_change_done.html',),  
                                                    name='password_change_done'),

    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='account/password_reset_form.html',
        email_template_name='account/password_reset_email.html',
        success_url='done/'
    ), name='password_reset'),

    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/password_reset_done.html'
    ), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/password_reset_confirm.html',
        success_url='profile/'
    ), name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='account/password_reset_complete.html'
    ), name='password_reset_complete'),
    path('student-registration/', views.StudentRegistrationView.as_view(), 
                        name='student-registration'),
    path('instructor-registration/', views.InstructorRegistrationView.as_view(), 
                        name='instructor-registration'),
    path('admin-registration/', views.AdminRegistrationView.as_view(), 
        name='admin-registration'),

    path('profile/', views.UserProfileDetailView.as_view(), name='userprofile-detail'),
    path('profile/edit/', views.UserProfileUpdateView.as_view(), name='userprofile-update'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('account/', include('account.urls')),
    path('', include('pages.urls')),
    path("student_dashboard/",include('student.urls')),
    path("instructor_dashboard/",include('instaructor.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base_home.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"/>
    <title>Blank page - Tabler - Premium and Open Source dashboard template with responsive and high quality UI.</title>
    <!-- CSS files -->
    <link href="{% static 'theme/css/tabler.min.css' %} " rel="stylesheet"/>
    <link href="{% static 'theme/css/tabler-flags.min.css' %} " rel="stylesheet"/>
    <link href="{% static 'theme/css/tabler-payments.min.css' %} " rel="stylesheet"/>
    <link href="{% static 'theme/css/tabler-vendors.min.css' %} " rel="stylesheet"/>
    <link href="{% static 'theme/css/demo.min.css' %} " rel="stylesheet"/>
   <link href="{% static 'theme/inter.css' %} " rel="stylesheet"/>
    <style>
      @import url('https://rsms.me/inter/inter.css');
      :root {
      	--tblr-font-sans-serif: 'Inter Var', -apple-system, BlinkMacSystemFont, San Francisco, Segoe UI, Roboto, Helvetica Neue, sans-serif;
      }
      body {
      	font-feature-settings: "cv03", "cv04", "cv11";
      }
    </style>
  </head>
  <body >
    <div class="page">
 

      <div class="page-wrapper">
   

        {% if user.is_authenticated %}
        <p>Welcome, {{ user.username }}!</p>
        <p>You are authenticated.</p>
        <!-- Display content for authenticated users -->
        {% else %}
        <p>You are not authenticated. Please log in. or create an account</p>
        <!-- Display content for non-authenticated users -->
        <a href="{% url 'account_user:login_account' %}">login</a>
        {% endif %}
    
   
    {% block content %}
        
    {% endblock content %}
    <footer class="footer footer-transparent d-print-none">
        <div class="container-xl">
          <div class="row text-center align-items-center flex-row-reverse">
            <div class="col-lg-auto ms-lg-auto">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item"><a href="https://tabler.io/docs" target="_blank" class="link-secondary" rel="noopener">Documentation</a></li>
                <li class="list-inline-item"><a href="./license.html" class="link-secondary">License</a></li>
                <li class="list-inline-item"><a href="https://github.com/tabler/tabler" target="_blank" class="link-secondary" rel="noopener">Source code</a></li>
                <li class="list-inline-item">
                  <a href="https://github.com/sponsors/codecalm" target="_blank" class="link-secondary" rel="noopener">
                    <!-- Download SVG icon from http://tabler-icons.io/i/heart -->
                    <svg xmlns="http://www.w3.org/2000/svg" class="icon text-pink icon-filled icon-inline" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M19.5 12.572l-7.5 7.428l-7.5 -7.428a5 5 0 1 1 7.5 -6.566a5 5 0 1 1 7.5 6.572" /></svg>
                    Sponsor
                  </a>
                </li>
              </ul>
            </div>
            <div class="col-12 col-lg-auto mt-3 mt-lg-0">
              <ul class="list-inline list-inline-dots mb-0">
                <li class="list-inline-item">
                  Copyright &copy; 2023
                  <a href="." class="link-secondary">Tabler</a>.
                  All rights reserved.
                </li>
                <li class="list-inline-item">
                  <a href="./changelog.html" class="link-secondary" rel="noopener">
                    v1.0.0-beta19
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </footer>

    </div>
  </div>
  <!-- Libs JS -->
  <!-- Tabler Core -->
  <!-- Libs JS -->
  <script src="{% static 'theme/libs/apexcharts/dist/apexcharts.min.js' %} " defer></script>
  <script src="{% static 'theme/libs/jsvectormap/dist/js/jsvectormap.min.js' %} " defer></script>
  <script src="{% static 'theme/libs/jsvectormap/dist/maps/world.js' %} " defer></script>
  <script src="{% static 'theme/libs/jsvectormap/dist/maps/world-merc.js' %} " defer></script>
  <!-- Tabler Core -->
  <script src="{% static 'theme/js/tabler.min.js' %} " defer></script>
  <script src="{% static 'theme/js/demo.min.js' %}" defer></script>
  <script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
  <script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
  <script src="{% static 'theme/libs/litepicker/dist/litepicker.js' %}" defer></script>
  <script src="{% static 'theme/libs/list.js/dist/list.js'%}" defer></script>
</body>
</html>